[build]
  command = ""
  publish = ".next"

[build.environment]
  NODE_VERSION = "18"
  NEXT_PUBLIC_API_URL = "https://healthcare-backend-v2-xp4h.onrender.com/api"

[[plugins]]
  package = "@netlify/plugin-nextjs"
